### ISSUE TITLE
無序清單在電腦上及手機上的點點不一樣

### ISSUE THREAD

**Issue by gnehs** [teacat/tocas#441]
![1498987753 0702 1729](https://user-images.githubusercontent.com/16719720/27768721-e4e4b082-5f4c-11e7-882a-d34eee21f51c.png)
左邊電腦 右邊是 Android 的 Chrome
https://tocas-ui.com/typography/#無序

**Comment by YamiOdymel** [comment]
試著在本地用最新版的 Tocas 測試看看，文件的版本可能沒更新，當初有修正這個問題

2017年7月2日 下午5:37，"棒棒勝" <notifications@github.com>寫道：

[image: 1498987753 0702 1729]
<https://user-images.githubusercontent.com/16719720/27768721-e4e4b082-5f4c-11e7-882a-d34eee21f51c.png>
左邊電腦 右邊是 Android 的 Chrome
https://tocas-ui.com/typography/#無序

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TeaMeow/TocasUI/issues/441>, or mute the thread

**Comment by gnehs** [comment]
等等試試

**Comment by gnehs** [comment]
修好了！謝謝
